<?php

namespace Tests\Feature;

use App\Models\Form;
use App\Models\User;
use Tests\GraphQlTestHelper;
use Tests\TestCase;

class FormFilterTest extends TestCase
{
    use GraphQlTestHelper;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        User::truncate();
        Form::truncate();
        $user = User::create([
            'name' => 'admin',
            'email' => 'admin2@admin.ru',
            'password' => 'password',
        ]);

        $form = Form::create([
            'name' => 'Nikita',
            'lastName' => 'Lipatov',
            'middleName' => 'Glebovich',
            'user_id' => $user->id
        ]);
    }

    public function test_form_cnt(){
        $cnt = Form::count();
        $this->assertEquals(1, $cnt);
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_get_forms()
    {
        $this->graphql('{forms{fio}}')
            ->assertJson([
                'data' => [
                    'forms' => [
                        ['fio' => 'Lipatov Nikita Glebovich']
                    ]
                ]
            ]);
    }

    public function test_get_form_by_fio()
    {
        $this->graphql('{forms(where:{fio:"Lipatov"}){fio}}')
            ->assertJson([
                'data' => [
                    'forms' => [
                        ['fio' => 'Lipatov Nikita Glebovich']
                    ]
                ]
            ]);
    }
}
