export const objectEventsMixin = {
  data: () => ({
    eventStages: [
      {
        stage: 1,
        text: 'Вид ремонта',
        disabled: true
      },
      {
        stage: 2,
        text: 'Выполнение обследования, подготовка и утверждение дефектного акта (дефектной ведомости)',
        p01: null,
        p02: null,
        p03: null,
        p04: null,
        p05: null,
        p06: null,
        end_stage: null,
        comment: null,
        exp_mon: null,
        comment_mon: null,
      },
      {
        stage: 3,
        text: 'Утверждение задания на проектирование, Подготовка проектно-сметной документации',
        p01: null,
        p02: null,
        p03: null,
        p04: null,
        p05: null,
        p06: null,
        end_stage: null,
        comment: null,
        exp_mon: null,
        comment_mon: null,
      },

      {
        stage: 4,
        text: 'Прохождение государственной экспертизы проектно-сметной документации',
        p01: null,
        p02: null,
        p03: null,
        p04: null,
        p05: null,
        p06: null,
        end_stage: null,
        comment: null,
        exp_mon: null,
        comment_mon: null,
      },
      {
        stage: 5,
        text: 'Выполнение строительно-монтажных работ',
        p01: null,
        p02: null,
        p03: null,
        p04: null,
        p05: null,
        p06: null,
        end_stage: null,
        comment: null,
        exp_mon: null,
        comment_mon: null,
      },
    ],
  }),
};
